### ISSUE TITLE
Not able to get totalToken

### ISSUE THREAD

**Issue by AnandSaran** [hrvojecukman/chat_gpt_flutter#4]
Hi, I have implemented createChatCompletionStream.
But in the StreamCompletionResponse not able to get the token information model UsageResponse.

**Comment by iBog** [comment]
As I see response objects in stream mode does not contain 'usage' section with tokens stats:
`{
    "id": "cmpl-7BO0U7TFWJVvEJAYVJWjsRTqZO2w1",
    "object": "text_completion",
    "created": 1682948246,
    "choices": [
        {
            "text": " indicators",
            "index": 0,
            "logprobs": null,
            "finish_reason": null
        }
    ],
    "model": "text-davinci-003"
}`
