### ISSUE TITLE
DioError ║ Status: 404 Not Found

### ISSUE THREAD

**Issue by AnandSaran** [hrvojecukman/chat_gpt_flutter#7]
createChatCompletionStream() return 404 error.

![image](https://user-images.githubusercontent.com/13350800/236794774-3f35a19a-58a3-49d5-be97-cd93ca2ef45f.png)

**Comment by berkayhh** [comment]
up

**Comment by AnandSaran** [comment]
HI @berkayhh 
 I found the issue.  For my Chat GPT account payment is not linked.
